include: package:flutter_lints/flutter.yaml

linter:
  rules:
    use_key_in_widget_constructors: false
    avoid_relative_lib_imports: true
    prefer_relative_imports: true
    hash_and_equals: false

